// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyColQ1y1QBjCSVM9beOGh5ao8W6wDKZIso',
    appId: '1:38213246262:web:d3fa461b866ddd8665e797',
    messagingSenderId: '38213246262',
    projectId: 'iot1-d86f0',
    authDomain: 'iot1-d86f0.firebaseapp.com',
    storageBucket: 'iot1-d86f0.firebasestorage.app',
    databaseURL:
        'https://iot1-d86f0-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXbLvZYDYdGJspgCwymFiHRyPBiHHdY4g',
    appId: '1:38213246262:android:f898d957489f2c6a65e797',
    messagingSenderId: '38213246262',
    projectId: 'iot1-d86f0',
    storageBucket: 'iot1-d86f0.firebasestorage.app',
    databaseURL:
        'https://iot1-d86f0-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABJiIRnZo6hq4d34IPf5Osch4YLDUVJGU',
    appId: '1:38213246262:ios:36ed68dee4beac2965e797',
    messagingSenderId: '38213246262',
    projectId: 'iot1-d86f0',
    storageBucket: 'iot1-d86f0.firebasestorage.app',
    databaseURL:
        'https://iot1-d86f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.mobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABJiIRnZo6hq4d34IPf5Osch4YLDUVJGU',
    appId: '1:38213246262:ios:36ed68dee4beac2965e797',
    messagingSenderId: '38213246262',
    projectId: 'iot1-d86f0',
    storageBucket: 'iot1-d86f0.firebasestorage.app',
    databaseURL:
        'https://iot1-d86f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyColQ1y1QBjCSVM9beOGh5ao8W6wDKZIso',
    appId: '1:38213246262:web:d2e715b021144b9b65e797',
    messagingSenderId: '38213246262',
    projectId: 'iot1-d86f0',
    authDomain: 'iot1-d86f0.firebaseapp.com',
    storageBucket: 'iot1-d86f0.firebasestorage.app',
    databaseURL:
        'https://iot1-d86f0-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
